### ISSUE TITLE
starting problem

### ISSUE THREAD

**Issue by sasa42** [hamish-milne/VT0#2]
in
Unity 2018.3.12f1
Unity 2019.1.0f1

 I 
- created a Plane 
- with NewMaterial and 
- imported a 8K texture (RGBA 32bit) to the Albedo.

*VT0 -> Virtualize Project* 
*VT0 -> Virtualize Shaders*
are not available

VTO -> Settings is available
i set there _MainTex to RGBA32 an applied.
In /Ressource there is the VT0Info written.

Do you have some tips what i do wrong?
There are no error in console. Everything fine.

I also imported the Unity Unlit Shader source and 
changed 
`tex2D(texture, uv)` to `VT0_sample(texture, uv)`

I stuck here.
Do you have an idea what could be the problem i have no
*VT0 -> Virtualize Project* 
*VT0 -> Virtualize Shaders*
?

**Comment by hamish-milne** [comment]
Thank you for your submission, but I'm afraid this project is very much WIP so I'm not surprised it doesn't work! I'll see if I have more time to work on it in the future.

**Comment by sasa42** [comment]
Thanks. Meantime i found out that there are no 
VT0 -> Virtualize Project
VT0 -> Virtualize Shaders
methods.

and tried further whith manual setting up an Unlit Shader.
I will keep on trying. 
The biggest problem for now is that i cannot trigger the build process of the virtual texure.
I placed some scripts in an Editor Folder to allow building.  I can build it. No errors.
But no virtual texture.
When you could add a simple mesh +material +simple unlit shader +texture it would be great.
